jdbcUrl=jdbc:sqlite:/opt/CurrencyConversion.db
driverClassName=org.sqlite.JDBC
poolName=currency-conversion
maximumPoolSize=16
minimumIdle=16
connectionTimeout=5000
validationTimeout=2000
maxLifetime=1500000
keepaliveTime=120000
transactionIsolation=TRANSACTION_READ_COMMITTED
autoCommit=true